<!-- footer.inc -->
<div class="container">
    <div class="row">
        <div class="col-sm-1 text-right" style="vertical-align:top">
            [% PROCESS gplus1.inc %]
        </div>
        <div class="col-sm-2 text-right" style="vertical-align:top">
            [% PROCESS fblike.inc %]
        </div>
    </div>
</div>
    <div id="footer">
      <div class="container">
        <p class="text-muted credit pull-right">[%copyright%]</p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="/bootstrap/holder.min.js"></script>

    [% PROCESS google_analytics.inc %]
  </body>
</html>
<!-- footer.inc -->
